name: 'Test Artifact Download'

on:
  push:
    branches:
    - main
  pull_request:
  
jobs:
  upload:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        shell: bash
    - name: create file
        run: echo "${{ github.run.id }}" > output.txt
    - uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: ./*txt
   download:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        shell: bash
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GH_TOKEN}}
        # Required, workflow file name or ID
        workflow: test.yml
        pr: ${{github.event.pull_request.number}}
    - name: read file
        run: cat output.txt
    
